version: '3.8'

services:

  posgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: localdb
      POSTGRES_USER: storeUser

networks:
  default: